### ISSUE TITLE
zotero-retracter-1.0.0.SVN.xpi should not be distributed to users

### ISSUE THREAD

**Issue by dstillman** [nikolausn/ReTrackers#1]
Thanks for creating a Zotero plugin. Unfortunately, this version has serious problems and shouldn't be distributed to users in its current state. As the lead developer of Zotero, I'd appreciate if you would take down the current XPI immediately.

You're overriding the main function that gets run when items are selected in Zotero, `ZoteroPane.itemSelected()`, and instead of calling a reference to the original function, as one would normally do when monkey-patching, you've duplicated the entire function (without attribution, in violation of the AGPL license) and added your own code. This is guaranteed to break Zotero in a future version, since you'll be overriding any code we add to that function.

You're also overriding the internal state of `Zotero.DataDirectory._dir` for some reason, which may cause serious problems for people using a custom data directory.

Finally, you haven't specified an `updateURL` in install.rdf, so you're not able to push updates or bug fixes, including fixes for these issues.

Since you're overriding Zotero code in a way that's guaranteed to break future versions and can't push updates, I'm afraid we're going to have to blacklist this extension version in the next Zotero release, but I'd appreciate if you could remove the XPI until you have a version available that fixes these problems.

**Comment by nikolausn** [comment]
Thank you for this concern, this input is really meaningful to us. We already deleted the XPI and will work hard to do things better without violating the license and Zotero feature.
We understand that this plugin is not for public usage for now, we are still in progress of realizing our idea into a working prototype and always improving the feature with hope it can be useful for Zotero users and community. 
As we are still working on this we haven’t included the auto update because it was mean for our internal use and evaluation right now.

Really thankful for Zotero community to develop a really cool tool for us,
